apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: update-registry-mirrors
  namespace: kube-system
  labels:
    app: update-registry-mirrors
spec:
  selector:
    matchLabels:
      name: update-registry-mirrors
  template:
    metadata:
      labels:
        name: update-registry-mirrors
    spec:
      hostPID: true
      initContainers:
        - name: update-registries
          image: de.icr.io/final-catalog/ubi9-minimal@sha256:80f3902b6dcb47005a90e14140eef9080ccc1bb22df70ee16b27d5891524edb2
          securityContext:
            privileged: true
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -euo pipefail

              CONFIG_FILE="/host/etc/containers/registries.conf.d/090-mirror-registry.conf"
              TMP_FILE="/host/tmp/registries.conf.tmp"
              MAPPING_FILE="/config/mapping.txt"

              mkdir -p /host/etc/containers/registries.conf.d

              if [[ ! -f "$MAPPING_FILE" ]]; then
                echo "mapping.txt not found"
                exit 1
              fi

              echo "# Generated by update-registry-mirrors DaemonSet" > "$TMP_FILE"

              LAST_SRC=""

              while IFS='=' read -r SRC MIRROR || [[ -n "$SRC" ]]; do
                [[ -z "$SRC" || -z "$MIRROR" ]] && continue

                # If source registry changed, start a new [[registry]] block
                if [[ "$SRC" != "$LAST_SRC" ]]; then
                  {
                    echo ""
                    echo "[[registry]]"
                    echo "location = \"$SRC\""
                  } >> "$TMP_FILE"

                  LAST_SRC="$SRC"
                fi

                {
                  echo ""
                  echo "[[registry.mirror]]"
                  echo "location = \"$MIRROR\""
                  echo "mirror-by-digest-only = true"
                } >> "$TMP_FILE"

              done < "$MAPPING_FILE"


              if [[ ! -f "$CONFIG_FILE" ]] || ! cmp -s "$TMP_FILE" "$CONFIG_FILE"; then
                echo "Registry config changed"
                mv "$TMP_FILE" "$CONFIG_FILE"
                chroot /host systemctl restart crio
              else
                echo "No registry changes detected"
                rm -f "$TMP_FILE"
              fi

          volumeMounts:
            - name: host
              mountPath: /host
            - name: mappings
              mountPath: /config

      containers:
        - name: sleep
          image: icr.io/ibm/alpine:latest
          command: ["/bin/sh", "-c"]
          args: ["while true; do sleep 3600; done"]

      volumes:
        - name: host
          hostPath:
            path: /
        - name: mappings
          configMap:
            name: registry-mapping

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
